name: Build and Tests

on: pull_request

jobs:
  build_tests_nuget_package:
    name: Build and Tests SSync Client and Server
    runs-on: ubuntu-latest
    steps:
    
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 8.0.x

        - uses: actions/checkout@v4
  
        - name: Restore Client
          run: dotnet restore ./src/SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Build Client
          run: dotnet build --no-restore  ./src/SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Clean
          run: dotnet clean

        - uses: actions/checkout@v4

        - name: Restore Server
          run: dotnet restore ./src/SSync.Server.LitebDB/SSync.Server.LitebDB.csproj

        - name: Build Server
          run: dotnet build --no-restore  ./src/SSync.Server.LitebDB/SSync.Server.LitebDB.csproj
          
        - name: Run Tests 
          run: dotnet test --no-build

