name: Build and Tests

on: pull_request

jobs:
  build_tests_nuget_package:
    name: Build and Tests SSync Client and Server
    runs-on: ubuntu-latest
    steps:
    
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 8.0.x

# project ssync client

        - uses: actions/checkout@v4
  
        - name: Restore Client
          run: dotnet restore ./src/SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Build Client
          run: dotnet build --no-restore  ./src/SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Clean
          run: dotnet clean

        - name: Run Unit Tests Client
          run: dotnet test ./test/SSync.Client.LiteDB.Tests/SSync.Client.LiteDB.Tests.csproj


# end project ssync client

# project ssync server

        - name: Restore Server
          run: dotnet restore ./src/SSync.Server.LitebDB/SSync.Server.LitebDB.csproj

        - name: Build Server
          run: dotnet build --no-restore  ./src/SSync.Server.LitebDB/SSync.Server.LitebDB.csproj

        - name: Run Unit Tests Server
          run: dotnet test ./test/SSync.Server.LitebDB.Tests/SSync.Server.LitebDB.Tests.csproj
          
        - name: Run Integration Tests Server
          run: dotnet test ./test/SSync.Server.LitebDB.Integration.Tests/SSync.Server.LitebDB.Integration.Tests.csproj  

# end project ssync server