name: Publish Nuget Packages

on:
    push:
      tags:
        - '*.*.**'
jobs:
  publish_nuget_package:
    name: Publish SSync Client
    runs-on: ubuntu-latest
    steps:
    
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 8.0.x

# project ssync client

        - uses: actions/checkout@v4
        - name: Set Version Client
          run: |
            set -i -e 's/{{Version}}/${{github.ref_name}}/' ./src.SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Restore Client
          run: dotnet restore ./src.SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Build Client
          run: dotnet build --no-restore  ./src.SSync.Client.LitebDB/SSync.Client.LitebDB.csproj


        - name: Test Client
          run: dotnet test --no-build --verbosity normal  ./src.SSync.Client.LitebDB/SSync.Client.LitebDB.csproj

        - name: Pack Client
          run: |
            dotnet pack ./src.SSync.Client.LitebDB/SSync.Client.LitebDB.csproj -c Release -o .output-client


        # - name: Publish Client
        #   env:
        #     API_KEY: ${{ secrets.NUGET_API_KEY_CLIENT }}    
        #   run: |
        #     dotnet nuget push output-client/*.nupkg --api-key $API_KEY --source -s https://api.nuget.org/v3/index.json --skip-duplicate

# end project ssync client

# project ssync server

        - uses: actions/checkout@v4
        - name: Set Version Server
          run: |
            set -i -e 's/{{Version}}/${{github.ref_name}}/' ./src.SSync.Server.LitebDB/SSync.Server.LitebDB.csproj

        - name: Restore Server
          run: dotnet restore ./src.SSync.Server.LitebDB/SSync.Server.LitebDB.csproj

        - name: Build Server
          run: dotnet build --no-restore  ./src.SSync.Server.LitebDB/SSync.Server.LitebDB.csproj


        - name: Test Server
          run: dotnet test --no-build --verbosity normal  ./src.SSync.Server.LitebDB/SSync.Server.LitebDB.csproj

        - name: Pack Server
          run: |
            dotnet pack ./src.SSync.Server.LitebDB/SSync.Server.LitebDB.csproj -c Release -o .output-server


        # - name: Publish Server
        #   env:
        #     API_KEY: ${{ secrets.NUGET_API_KEY_SERVER }}    
        #   run: |
        #     dotnet nuget push output-server/*.nupkg --api-key $API_KEY --source -s https://api.nuget.org/v3/index.json --skip-duplicate

# end project ssync server
        